"""add client model

Revision ID: 3e9728a8561c
Revises: 9c7ccb800432
Create Date: 2018-02-26 11:10:32.204754

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3e9728a8561c'
down_revision = '9c7ccb800432'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_client',
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=22), nullable=False),
    sa.Column('secret_key', sa.Unicode(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('kiroku_user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiroku_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('api_client')
    # ### end Alembic commands ###
