"""note model

Revision ID: b0abd0e8c778
Revises: 3e9728a8561c
Create Date: 2018-02-26 16:37:32.209738

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b0abd0e8c778'
down_revision = '3e9728a8561c'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('content', sa.Unicode(length=10000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('api_client', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('note')
    # ### end Alembic commands ###
